INSERT INTO departments VALUES(1, 1,'InformationDesign', NULL);
INSERT INTO departments VALUES(2, 3,'InformationDesign', NULL);
INSERT INTO departments VALUES(3, 8,'InformationDesign', NULL);
INSERT INTO departments VALUES(4, 6,'InformationDesign', NULL);
INSERT INTO departments VALUES(5, 5,'InformationDesign', NULL);
INSERT INTO departments VALUES(6, 2,'InformationDesign', NULL);
INSERT INTO departments VALUES(7, 2,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(8, 13,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(9, 8,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(10, 4,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(11, 6,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(12, 11,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(13, 3,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(14, 5,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(15, 9,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(16, 1,'InformationDevelopment', NULL);
INSERT INTO departments VALUES(17, 1,'IT Documentation', NULL);
INSERT INTO departments VALUES(18, 4,'IT Documentation', NULL);
INSERT INTO departments VALUES(19, 8,'IT Documentation', NULL);
INSERT INTO departments VALUES(20, 11,'IT Documentation', NULL);
INSERT INTO departments VALUES(21, 12,'IT Documentation', NULL);
INSERT INTO departments VALUES(22, 7,'IT Documentation', NULL);
INSERT INTO departments VALUES(23, 9,'IT Documentation', NULL);
INSERT INTO departments VALUES(24, 15,'IT Documentation', NULL);
INSERT INTO departments VALUES(25, 2,'IT Documentation', NULL);
INSERT INTO departments VALUES(26, 1,'DocumentationAnalysis', NULL);
INSERT INTO departments VALUES(27, 3,'DocumentationAnalysis', NULL);
INSERT INTO departments VALUES(28, 5,'DocumentationAnalysis', NULL);
INSERT INTO departments VALUES(29, 7,'DocumentationAnalysis', NULL);
INSERT INTO departments VALUES(30, 9,'DocumentationAnalysis', NULL);
INSERT INTO departments VALUES(31, 11,'DocumentationAnalysis', NULL);
INSERT INTO departments VALUES(32, 13,'DocumentationAnalysis', NULL);
INSERT INTO departments VALUES(33, 15,'DocumentationAnalysis', NULL);
INSERT INTO departments VALUES(34, 2,'DocumentationAnalysis', NULL);
