//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_questions
    {
        public int question_id { get; set; }
        public int feedback_id { get; set; }
        public Nullable<int> result { get; set; }
        public string comment { get; set; }
    
        public virtual feedbacks feedbacks { get; set; }
        public virtual questions questions { get; set; }
    }
}
