//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedbacks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public feedbacks()
        {
            this.feedback_questions = new HashSet<feedback_questions>();
        }
    
        public int feedback_id { get; set; }
        public Nullable<System.DateTime> initiated { get; set; }
        public Nullable<System.DateTime> received { get; set; }
        public Nullable<int> project_id { get; set; }
        public string Id { get; set; }
    
        public virtual Projects Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<feedback_questions> feedback_questions { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
